port: 8000
game_settings:
  player_health: 100
  player_speed: 1000
  weapons:
    knife:
      damage: 3
      range: 1
      precision: 1
    glock:
      damage: 10
      range: 5
      precision: 0.7
    ak47:
      damage: 8
      range: 5
      precision: 0.6
    m3:
      damage: 5
      range: 3
      precision: 0.5
    awp:
      damage: 20
      range: 10
      precision: 0.7
